### ISSUE TITLE
Error value out of range

### ISSUE THREAD

**Issue by dkeza** [SebastiaanKlippert/go-foxpro-dbf#1]
When a numeric field in DBF has 10 Digit Value, for example, Field N(12) has number 9999999999, then i receive this error:

strconv.ParseInt: parsing "9999999999": value out of range

Here is [Gist](https://gist.github.com/dkeza/347a50555c45220286dfcd5f77499773) with test programs to reproduce this error.

**Comment by SebastiaanKlippert** [comment]
Thanks for reporting this.

I will check if I can reproduce and fix this.

**Comment by SebastiaanKlippert** [comment]
According to https://msdn.microsoft.com/en-us/library/aa975385(v=vs.71).aspx only 32 bit integers are supported.
>   	Minimum value of an integer 	-2,147,483,647
> 	Maximum value of an integer 	2,147,483,647

I am certain that in the application we wrote this import for, we only support 32 bit ints, never 64 bit.
That is why I use ParseInt with a bitsize of 32 in Go.

I am not sure I can change this without consequences. On the other hand, this is only an importer so if a Database contains 64 bit ints it should not really matter in Go, the field length for these fields should also be 64 in that case so it looks like reading it already works.

Which application do you use that can read 64 bit int?

I will come back to this!

**Comment by dkeza** [comment]
I am using Go to write small service, which uses database from my main Visual FoxPro 9.0 application. In this field is stored some number, which is used in Application, but not for arithmetical operations, it is just some value which is used in application.
I didn't want to get this field from table, but as i have seen in debugger, when error occurs, function quits, so i can't read other fields which I need.
Maybe it is possible that in this case, when limitations of Int32 are reached, that that field would be ignored? Or maybe converted to string?

**Comment by SebastiaanKlippert** [comment]
Thanks for the info.

It seems like my previous comment was incorrect, the limitation of 32 bits is for fields of type I.
N values are stored as strings up to 32 characters long, so my implementation of these types is incorrect.

In fact, it looks like this bug only affects values without decimals, I treat F fields as 64 bits as well.
I will fix it.

**Comment by SebastiaanKlippert** [comment]
Ok, it was a small fix,can you let me now if this helps, if not feel to re-open the issue!
If it does not work, can give me the DBF you created with your gist code? My DBF editor does not allow me to enter Numeric values with more than 9 digits before the decimals... So that is probably why I misinterpreted the specs in the first place.
But I am confident this will resolve your isue!

Thanks again for the report.

**Comment by dkeza** [comment]
I can confirm, that it is working now as expected.

Thank you!
