### ISSUE TITLE
Error: panic: Untested DBF file version: 3 (3 hex)

### ISSUE THREAD

**Issue by vsile** [SebastiaanKlippert/go-foxpro-dbf#3]
I get the error message:
panic: Untested DBF file version: 3 (3 hex)

What's wrong with my DBF-file?

I open it in LibreOffice (coding DOS/OS2-866/русский) and get:

```
ACTSTATID,N,19,5    |       NAME,C,100
---------------------------------------------
0,00000             |       Не актуальный
---------------------------------------------
1,00000             |       Актуальный
```

**Comment by SebastiaanKlippert** [comment]
Hi, 

I don't think anything is wrong with your DBF file, but it probaly is not a FoxPro file, it looks like a FoxBase or DBase III file.

Like it says in the readme, this package has only been tested wit FoxPro files. But that does not mean your file will not work.
If you would like to try if it can still read your file, you can modify function `validFileVersion` https://github.com/SebastiaanKlippert/go-foxpro-dbf/blob/master/reader.go#L699 to return no error on value 0x03 (or have it always return nil).

Let me know if that works. I might create a setting for which files to accept, or if you have other files in this format and want to add some tests this package might support these files by default.

**Comment by vsile** [comment]
@SebastiaanKlippert, thank you! I just commented next code
```
//Check if the fileversion flag is expected, expand validFileVersion if needed
if err := validFileVersion(header.FileVersion); err != nil {
	return nil, err
}
```
And it works!

**Comment by SebastiaanKlippert** [comment]
I have made the version checking function exported, so you can now do something like

```go
	ValidFileVersionFunc = func(version byte) error {
		if version == 0x03 {
			return nil
		}
		return errors.New("not 0x03")
	}
```
before opening the file.

But that sets the validation function on package level, so for all files you will open next.
You can revert it with 
```go
defer func() { ValidFileVersionFunc = validFileVersion }()
```
Not the cleanest option, but for most people this will be OK I guess.
